_target_: src.models.vit_module.ViTModule
learning_rate: 5e-3
nhead: 4
dim_feedforward: 32
blocks: 4
mlp_head_units: [32, 16]
n_classes: 10
img_size: [32, 32]
patch_size: [4, 4]
n_channels: 3
d_model: 32
