_target_: src.models.vit_module.ViTModule
learning_rate: 1e-4
nhead: 4
dim_feedforward: 256
blocks: 4
mlp_head_units: [256, 128]
n_classes: 100
img_size: [32, 32]
patch_size: [4, 4]
n_channels: 3
d_model: 128
